language: node_js
node_js:
  - node
env:
  global:
    - CODECOV_TOKEN=5e596f9e-8f4b-4a33-939e-cb3d95d85b05

cache: yarn

script:
  - ./bin/run --version
  - ./bin/run --help
  - yarn run test


after_success:
  - ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
  - bash < (curl -s https://codecov.io/bash)
