language: node_js
node_js:
  - node

cache: yarn

script:
  - ./bin/run --version
  - ./bin/run --help
  - yarn run test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage
